public class CustomerAccessPoint {
    public void acceptQuotation(){
        //Code to accept the quotation provided by the insurer and proceed with the policy purchase process
    }
    public void viewHistory(){
        //Code to view the history of quotations received by the user
    }
    public void downloadPolicyBond(){
        //Code to download the policy bond and GST invoice
    }
    public void viewStatement(){
        //Code to view the policy running statement
    }
    public void addDeleteMembers(){
        //Code to add or delete members from the policy
    }
    public void raiseRequests(){
        //Code to raise non-monetary policy service requests
    }
    public void generateValuationReport(){
        //Code to generate an AS-15 valuation report
    }
    public void requestConversion(){
        //Code to request a policy conversion
    }
    public void intimateClaim(){
        //Code to intimate claim(s) through the system
    }
    public void uploadProofs(){
        //Code to upload proof of documents
    }
    
}